version: "3"
services:
  express:
    image: archanpatkar/expressservice:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.3"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet: